upstream julchek_app {
    # Контейнер julchek (docker-compose: "4400:80")
    server 127.0.0.1:4400;
}

server {
    server_name julchek.ru www.julchek.ru;

    location / {
        proxy_pass http://julchek_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

}
